DROP TABLE IF EXISTS offer_skill CASCADE;
DROP TABLE IF EXISTS candidate_skill CASCADE;
DROP TABLE IF EXISTS candidate CASCADE;
DROP TABLE IF EXISTS offer CASCADE;
DROP TABLE IF EXISTS employer CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS city CASCADE;

DROP TABLE IF EXISTS devfinder_user CASCADE;
DROP TABLE IF EXISTS devfinder_role CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;